spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes
              uri: http://localhost:8082
              predicates:
                - Path=/api/clientes,/api/clientes/**

            - id: mascotas
              uri: http://localhost:8082
              predicates:
                - Path=/api/mascotas,/api/mascotas/**

            - id: Box
              uri: http://localhost:8083
              predicates:
                - Path=/api/boxes,/api/boxes/**
                
            - id: HoraMedica
              uri: http://localhost:8083
              predicates:
                - Path=/api/horas,/api/horas/**

            - id: Sucursal
              uri: http://localhost:8083
              predicates:
                - Path=/api/sucursales,/api/sucursales/**

            - id: Consulta
              uri: http://localhost:8084
              predicates:
                - Path=/api/consultas,/api/consultas/**

            - id: FichaClinica
              uri: http://localhost:8084
              predicates:
                - Path=/api/ficha,/api/ficha/**



            - id: Auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth,/api/auth/**
            
            - id: usuarios
              uri: http://localhost:8081
              predicates:
                - Path=/api/usuarios,/api/usuarios/**

            - id: movimientos
              uri: http://localhost:8085
              predicates:
                - Path=/api/movimientos,/api/movimientos/**

            - id: pedidos
              uri: http://localhost:8085
              predicates:
                - Path=/api/pedidos,/api/pedidos/**

            - id: productos
              uri: http://localhost:8085
              predicates:
                - Path=/api/productos,/api/productos/**

            - id: proveedor
              uri: http://localhost:8085
              predicates:
                - Path=/api/proveedor,/api/proveedor/**

            - id: stock
              uri: http://localhost:8085
              predicates:
                - Path=/api/stock,/api/stock/**

            - id: carrito
              uri: http://localhost:8086
              predicates:
                - Path=/api/carrito,/api/carrito/**

            - id: documentos
              uri: http://localhost:8086
              predicates:
                - Path=/api/documentos,/api/documentos/**

            - id: ventas
              uri: http://localhost:8086
              predicates:
                - Path=/api/ventas,/api/ventas/**



            - id: Notificaciones
              uri: http://localhost:8088
              predicates:
                - Path=/api/notificaciones,/api/notificaciones/** 

            - id: Soporte
              uri: http://localhost:8087
              predicates:
                - Path=/api/soportes,/api/soportes/**

            - id: Soporte
              uri: http://localhost:8087
              predicates:
                - Path=/soportes/{soporteId}/mensajes,/soportes/{soporteId}/mensajes/**

            - id: Reportes
              uri: http://localhost:8089
              predicates:
                - Path=/api/reportes,/api/reportes/**


server:
  port: 8090