spring.application.name=Inventario
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/db_veterinaria_inventario?useSSL=false
spring.datasource.username=tu_usuario
spring.datasource.password=tu_clave
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672